[project]
name = "cloud-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "uvicorn[standard]>=0.52.1",
]

[dependency-groups]
dev = [
    "locust>=2.46.3",
    "pytest>=9.1.1",
    "pandas>=2.2",
    "matplotlib>=3.9",
]
